apps : app.json
usr_id : <>
pasword :<>
db_name : Automation
username :<>
password : <>
security_token : <>
client_id : <>
domain : test
threatmodel_api : https://wwwin-tbv2.cisco.com/api/v1/threatmodels/
sts_uri : https://cloudsso.cisco.com/idp/sts.wst
instance : cisco
threatmodel_api_data : threatmodeldata.json
www_git_token : <>
wwwin_git_token : <>
esp_api : https://cisco.service-now.com/api/now/table/cmdb_ci_business_app?sysparm_query=sys_class_name%3Dcmdb_ci_business_app%5Eu_service_offering.u_service_name.owned_by%3D14c09413dba93e0caa2bf8621f961924%5Eoperational_statusIN6%2C1&sysparm_display_value=true&sysparm_exclude_reference_link=true&sysparm_fields=sys_id%2Cname%2Coperational_status%2Cinstall_type%2Cu_service_offering%2Cu_service_offering.u_service_name%2Cu_service_offering.u_service_name.owned_by
esp_app_details : https://cisco.service-now.com/api/now/table/cmdb_ci_business_app?sysparm_query=nameLIKE{0}&sysparm_display_value=true&sysparm_fields=name%2C%20u_responsibility_manager%2C%20sys_id%2C%20u_service_offering&sysparm_limit=1
business_criticality : https://cisco.service-now.com/api/now/table/u_cmdb_ci_cisco_business_application?sysparm_query=u_business_application.nameLIKE{0}&sysparm_display_value=true&sysparm_fields=u_res_business_criticality&sysparm_limit=1
